import createClient from "openapi-fetch";
import type { paths } from "./schema"; // generated by openapi-typescript
import { API_BASE_URL } from "./config";
import { ensureToken } from "@/auth";

const client = createClient<paths>({ baseUrl: API_BASE_URL });

// Every request except the login call itself needs the API key in the
// `authorization` header (see securitySchemes.ApiKeyAuth in schema.yml —
// it's a raw apiKey header, not an HTTP "Bearer " token). This middleware
// attaches it automatically to every client.GET/POST/etc. call made
// through this client, so individual components no longer fetch and
// attach the token themselves.
client.use({
  onRequest: async ({ request, schemaPath }) => {
    if (schemaPath === "/v1/auth/authorize") {
      return;
    }
    const token = await ensureToken();
    const headers = new Headers(request.headers);
    headers.set("authorization", token);
    return new Request(request, { headers });
  },
});

export default client;
