import createClient from "openapi-fetch";
import type { paths } from "./schema"; // generated by openapi-typescript

const client = createClient<paths>({ baseUrl: "https://api-servicios.sofse.gob.ar/" });

export default client;